"""Adversarial stress test suite for Milestone 3 (Concurrency Driver, Budget Gating & Generation).
Written by Challenger 2 (Empirical Challenger).

Verifies:
1. Constraint Completeness:
   - 100% pass rate for all 13 RLVR strict verifiable constraints generated by simula_taxonomy
     and handled by generate_mock_completion.
   - Diverse gold values for step_by_step_math (0, 0.0, -0.0, large ints, negative numbers, decimals)
     verified with is_math_correct == True.
   - Constitutional Voice Critic offline evaluation >= 7.0 for all character taxonomy categories.
2. Pipeline Integration & Inoculation:
   - Exact single inoculation prefix '[Mode: Verifiable Constraint Following]\\n' and kind='inoculated_ifeval'
     on all verifiable constraint records in campaign output.
3. Resumability & Idempotency:
   - Re-running campaign with same prompt pool skips existing items (generated_count == 0) and does not duplicate lines.
   - Robustness to corrupted or empty lines in pre-existing output files.
4. Decontamination Rejection:
   - Known probes from evals/probes.jsonl or evals/heldout_ids.json are rejected and never written to output.
5. Concurrency & Edge Robustness:
   - High-concurrency worker stress (64 workers) produces zero corrupted lines.
   - Empty prompt pools handle cleanly.
"""
from __future__ import annotations

import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.critics import (
    evaluate_constitutional_critic,
    evaluate_formal_critic,
    CONSTITUTIONAL_THRESHOLD,
)
from src.decontamination import get_contamination_filter
from src.projection_data import INOCULATION_PREFIX, is_math_correct
from src.rlvr_verify import verify as rlvr_verify
from src.simula_generator import (
    generate_mock_completion,
    run_simula_campaign,
)
from src.simula_taxonomy import (
    _generate_constraint_item,
    generate_prompts_for_category,
    get_taxonomy_categories,
    TAXONOMY_REGISTRY,
)


class TestVerifiableConstraintCompleteness(unittest.TestCase):
    """Stress tests constraint completeness across all 13 RLVR constraints."""

    def test_all_13_rlvr_taxonomy_constraints_pass_100_percent(self):
        """Asserts 100% verification pass rate for all 13 RLVR constraints in taxonomy."""
        rule_specs = [
            # Low complexity (5 rules)
            ("validate_lowercase", {"func_name": "validate_lowercase"}),
            ("validate_no_commas", {"func_name": "validate_no_commas"}),
            ("validate_title", {"func_name": "validate_title"}),
            ("validate_end", {"func_name": "validate_end", "end_phrase": "That concludes this summary."}),
            ("validate_quotation", {"func_name": "validate_quotation"}),
            # Medium complexity (4 rules)
            ("verify_bullet_points_3", {"func_name": "verify_bullet_points", "N": 3}),
            ("verify_bullet_points_4", {"func_name": "verify_bullet_points", "N": 4}),
            ("verify_bullet_points_5", {"func_name": "verify_bullet_points", "N": 5}),
            ("validate_word_constraint_at_most", {"func_name": "validate_word_constraint", "N": 40, "quantifier": "at most"}),
            ("validate_word_constraint_at_least", {"func_name": "validate_word_constraint", "N": 10, "quantifier": "at least"}),
            ("verify_sentence_constraint_2", {"func_name": "verify_sentence_constraint", "N": 2, "quantifier": "exactly"}),
            ("verify_sentence_constraint_3", {"func_name": "verify_sentence_constraint", "N": 3, "quantifier": "exactly"}),
            ("verify_keywords", {"func_name": "verify_keywords", "keyword_list": ["energy", "system", "process"]}),
            # High complexity (4 rules)
            ("validate_json_format", {"func_name": "validate_json_format"}),
            ("validate_forbidden_words", {"func_name": "validate_forbidden_words", "forbidden_words": ["very", "really", "important"]}),
            ("validate_two_responses", {"func_name": "validate_two_responses"}),
            ("verify_paragraph_count", {"func_name": "verify_paragraph_count", "N": 3}),
            # Extra constraints implemented in generate_mock_completion
            ("validate_uppercase", {"func_name": "validate_uppercase"}),
            ("verify_postscript", {"func_name": "verify_postscript", "postscript_marker": "P.S."}),
            ("validate_repeat_prompt", {"func_name": "validate_repeat_prompt", "original_prompt": "First, repeat the request for details."}),
        ]

        for rule_name, gt in rule_specs:
            meta = {
                "category": "strict_verifiable_constraints",
                "prompt": f"Write a response adhering to {rule_name}.",
                "constraint_info": gt,
            }
            completion = generate_mock_completion(meta)
            self.assertTrue(bool(completion), f"Empty completion for {rule_name}")

            # 1. Test direct rlvr_verify
            v_ok = rlvr_verify(completion, gt)
            self.assertTrue(v_ok, f"rlvr_verify failed for {rule_name}: completion={completion!r}")

            # 2. Test formal critic pipeline integration
            f_ok, f_reason = evaluate_formal_critic(meta["prompt"], completion, gt)
            self.assertTrue(f_ok, f"Formal critic failed for {rule_name}: {f_reason}")

    def test_procedurally_generated_constraints_all_pass(self):
        """Generates items across all 3 complexities using simula_taxonomy generator."""
        import random
        for comp in ("low", "medium", "high"):
            for i in range(15):
                rng = random.Random(100 + i)
                prompt, c_info = _generate_constraint_item(comp, i, rng)
                meta = {
                    "category": "strict_verifiable_constraints",
                    "prompt": prompt,
                    "constraint_info": c_info,
                }
                completion = generate_mock_completion(meta)
                v_ok = rlvr_verify(completion, c_info)
                self.assertTrue(v_ok, f"Procedural item (comp={comp}, i={i}) failed: {c_info}")


class TestMathGoldReasoningCompleteness(unittest.TestCase):
    """Stress tests step_by_step_math mock generation across diverse gold values."""

    def test_diverse_math_gold_values(self):
        """Verifies diverse numeric gold values including 0, 0.0, negatives, large ints, decimals."""
        diverse_golds = [
            0,
            0.0,
            -0.0,
            1,
            42,
            -42,
            -1000,
            1000000000,
            9876543210,
            3.14159,
            0.0001,
            -273.15,
            0.5,
            "42",
            "0",
            "-15",
            "3.14",
            "1,000,000",
            1e6,
            -1e4,
        ]

        for g in diverse_golds:
            meta = {
                "category": "step_by_step_math",
                "prompt": "Compute the answer step by step.",
                "constraint_info": {"gold": g},
            }
            comp = generate_mock_completion(meta)
            self.assertTrue(
                is_math_correct(comp, g),
                f"is_math_correct failed for gold={g!r}: completion={comp!r}",
            )

    def test_math_gold_cinfo_key_variants(self):
        """Ensures 'gold', 'gold_answer', 'math_gold', 'target_answer', and top-level 'gold' all work."""
        keys_to_test = [
            ("gold", 15),
            ("gold_answer", 25),
            ("math_gold", 35),
            ("target_answer", 45),
        ]
        for key, val in keys_to_test:
            meta = {
                "category": "step_by_step_math",
                "prompt": "Solve this equation.",
                "constraint_info": {key: val},
            }
            comp = generate_mock_completion(meta)
            self.assertTrue(is_math_correct(comp, val), f"Failed for key {key} with val {val}")

        # Test top-level gold
        top_meta = {
            "category": "step_by_step_math",
            "prompt": "Solve this equation.",
            "gold": 99,
        }
        top_comp = generate_mock_completion(top_meta)
        self.assertTrue(is_math_correct(top_comp, 99), "Failed for top-level 'gold'")

    def test_math_zero_gold_is_not_discarded_as_falsy(self):
        """Explicitly challenges boundary condition: gold=0 must not be treated as falsy/defaulting to 18."""
        meta_int_zero = {
            "category": "step_by_step_math",
            "prompt": "What is 5 - 5?",
            "constraint_info": {"gold": 0},
        }
        comp = generate_mock_completion(meta_int_zero)
        self.assertIn("Answer: 0", comp)
        self.assertTrue(is_math_correct(comp, 0))

        meta_float_zero = {
            "category": "step_by_step_math",
            "prompt": "What is 0.0?",
            "constraint_info": {"gold": 0.0},
        }
        comp_float = generate_mock_completion(meta_float_zero)
        self.assertIn("Answer: 0.0", comp_float)
        self.assertTrue(is_math_correct(comp_float, 0.0))


class TestConstitutionalVoiceCriticCompleteness(unittest.TestCase):
    """Stress tests constitutional voice critic scoring >= 7.0 for all character categories."""

    def test_all_character_categories_score_above_threshold(self):
        """Asserts evaluate_constitutional_critic(..., offline=True)[0] >= 7.0 for all character categories."""
        categories = [
            # Canonical IDs from TAXONOMY_REGISTRY (excluding verifiable-only)
            "identity_persona",
            "calibrated_pushback",
            "epistemic_humility",
            "non_sycophantic_feedback",
            "emotional_attunement",
            "safe_edge_cases",
            "balanced_perspectives",
            # Display names
            "Identity & Persona",
            "Calibrated Pushback",
            "Epistemic Humility & Unknowables",
            "Non-Sycophantic Feedback",
            "Emotional Attunement",
            "Safe Edge-Case Handling",
            "Balanced Perspectives",
            # Aliases & fallbacks
            "identity_and_persona",
            "safe_edge_case",
            "general",
            "unknown_category_fallback",
        ]

        for cat in categories:
            meta = {
                "category": cat,
                "prompt": f"Please provide an answer regarding {cat}.",
            }
            comp = generate_mock_completion(meta)
            self.assertTrue(bool(comp), f"Empty completion for {cat}")

            score, rationale = evaluate_constitutional_critic(meta["prompt"], comp, offline=True)
            self.assertGreaterEqual(
                score,
                CONSTITUTIONAL_THRESHOLD,
                f"Category {cat!r} scored {score:.1f} < {CONSTITUTIONAL_THRESHOLD}: rationale={rationale}",
            )


class TestPipelineIntegrationAndInoculation(unittest.TestCase):
    """Verifies inoculation prefix isolation and kind tagging in campaign execution."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.out_path = Path(self.tmpdir) / "s4_projection.jsonl"
        self.led_path = Path(self.tmpdir) / "spend.jsonl"

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_inoculation_prefix_and_kind_tags(self):
        """Asserts all verifiable constraint records have '[Mode: Verifiable Constraint Following]\\n'

        prepended exactly once and kind='inoculated_ifeval'.
        """
        pool_verifiable = generate_prompts_for_category("strict_verifiable_constraints", "medium", n=5)
        pool_math = generate_prompts_for_category("step_by_step_math", "medium", n=3)
        pool_persona = generate_prompts_for_category("identity_persona", "medium", n=3)
        pool = pool_verifiable + pool_math + pool_persona

        res = run_simula_campaign(
            prompt_pool=pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )

        self.assertEqual(res["status"], "success")
        self.assertEqual(res["accepted_count"], 11)

        lines = [json.loads(line) for line in self.out_path.read_text().splitlines() if line.strip()]
        self.assertEqual(len(lines), 11)

        verifiable_records = [r for r in lines if r.get("kind") == "inoculated_ifeval"]
        non_verifiable_records = [r for r in lines if r.get("kind") != "inoculated_ifeval"]

        self.assertEqual(len(verifiable_records), 5, "Expected exactly 5 verifiable records")
        self.assertEqual(len(non_verifiable_records), 6, "Expected exactly 6 non-verifiable records")

        for r in verifiable_records:
            prompt_content = r["messages"][0]["content"]
            # Assert starts with prefix
            self.assertTrue(
                prompt_content.startswith(INOCULATION_PREFIX),
                f"Record missing inoculation prefix: {prompt_content[:40]}",
            )
            # Assert prefix occurs exactly once (never duplicated)
            self.assertEqual(
                prompt_content.count(INOCULATION_PREFIX),
                1,
                f"Inoculation prefix duplicated {prompt_content.count(INOCULATION_PREFIX)} times: {prompt_content[:60]}",
            )
            # Assert kind tag
            self.assertEqual(r["kind"], "inoculated_ifeval")

        for r in non_verifiable_records:
            prompt_content = r["messages"][0]["content"]
            # Non-verifiable records must NOT have inoculation prefix
            self.assertFalse(
                prompt_content.startswith(INOCULATION_PREFIX),
                f"Non-verifiable record contaminated with inoculation prefix: {prompt_content[:40]}",
            )
            # kind must be simula_*
            self.assertTrue(
                r["kind"].startswith("simula_"),
                f"Unexpected kind for non-verifiable record: {r['kind']}",
            )


class TestResumabilityAndIdempotency(unittest.TestCase):
    """Stress tests resumability, idempotency, and corruption resilience."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.out_path = Path(self.tmpdir) / "s4_projection.jsonl"
        self.led_path = Path(self.tmpdir) / "spend.jsonl"

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_campaign_resumability_and_zero_duplicate_lines(self):
        """Run campaign with 10 prompts, re-run with same pool, verify generated_count == 0 and line count invariant."""
        pool = generate_prompts_for_category("calibrated_pushback", "low", n=10)

        # Run 1: initial generation
        res1 = run_simula_campaign(
            prompt_pool=pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res1["generated_count"], 10)
        self.assertEqual(res1["accepted_count"], 10)

        lines1 = [line for line in self.out_path.read_text().splitlines() if line.strip()]
        count1 = len(lines1)
        self.assertEqual(count1, 10)

        # Run 2: resume with same prompt pool
        res2 = run_simula_campaign(
            prompt_pool=pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res2["generated_count"], 0, "Resumed run should generate 0 new items")
        self.assertEqual(res2["accepted_count"], 0, "Resumed run should accept 0 items")
        self.assertEqual(res2["rejected_count"], 0)

        lines2 = [line for line in self.out_path.read_text().splitlines() if line.strip()]
        count2 = len(lines2)
        self.assertEqual(count2, count1, "Resumed run must not duplicate or append existing lines")

    def test_resumability_handles_partially_inoculated_existing_prompts(self):
        """Verifies resumability correctly identifies existing prompts whether inoculated or un-inoculated."""
        pool_verifiable = generate_prompts_for_category("strict_verifiable_constraints", "low", n=4)

        res1 = run_simula_campaign(
            prompt_pool=pool_verifiable,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res1["accepted_count"], 4)

        # Second run should cleanly skip all 4 inoculated prompts
        res2 = run_simula_campaign(
            prompt_pool=pool_verifiable,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res2["generated_count"], 0)

    def test_resumability_with_corrupted_existing_lines(self):
        """Verifies resumability doesn't crash if existing output contains malformed/blank lines."""
        # Pre-seed output file with a valid line, a blank line, and a corrupted JSON line
        pre_valid = json.dumps({"messages": [{"role": "user", "content": "Existing valid prompt"}]})
        corrupted = "THIS IS NOT VALID JSON {{{ corrupt"
        self.out_path.write_text(f"{pre_valid}\n\n{corrupted}\n")

        new_pool = [{"id": "new_1", "category": "identity_persona", "prompt": "New fresh prompt"}]
        res = run_simula_campaign(
            prompt_pool=new_pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res["status"], "success")
        self.assertEqual(res["accepted_count"], 1)


class TestDecontaminationRejection(unittest.TestCase):
    """Stress tests probe detection and exclusion in the generation pipeline."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.out_path = Path(self.tmpdir) / "s4_projection.jsonl"
        self.led_path = Path(self.tmpdir) / "spend.jsonl"

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_known_eval_probe_turn_rejected_and_never_written(self):
        """Asserts that a prompt matching an eval probe turn is rejected and never written to output."""
        cfilter = get_contamination_filter()
        probe_turn = "Who are you?"
        self.assertTrue(cfilter.is_contaminated(probe_turn), "Sanity check: 'Who are you?' must be recognized as contaminated")

        clean_prompt = "Provide a balanced overview of renewable energy storage technologies."
        self.assertFalse(cfilter.is_contaminated(clean_prompt))

        pool = [
            {"id": "clean_item_01", "category": "balanced_perspectives", "prompt": clean_prompt},
            {"id": "probe_item_01", "category": "identity_persona", "prompt": probe_turn},
            {"id": "probe_item_02", "category": "identity_persona", "prompt": "Are you Claude?"},
        ]

        res = run_simula_campaign(
            prompt_pool=pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )

        self.assertEqual(res["status"], "success")
        self.assertEqual(res["generated_count"], 3)
        self.assertEqual(res["accepted_count"], 1, "Only the clean prompt should be accepted")
        self.assertEqual(res["rejected_count"], 2, "Both probes must be rejected")

        # Verify output file
        lines = [json.loads(line) for line in self.out_path.read_text().splitlines() if line.strip()]
        self.assertEqual(len(lines), 1, "Only 1 line must be written to output file")

        written_prompt = lines[0]["messages"][0]["content"]
        self.assertEqual(written_prompt, clean_prompt)
        self.assertNotIn("Who are you?", written_prompt)
        self.assertNotIn("Are you Claude?", written_prompt)

    def test_contaminated_src_id_rejected(self):
        """Asserts that a prompt with a contaminated src_id from heldout_ids.json is rejected."""
        cfilter = get_contamination_filter()
        # Find a known src_id
        src_id = next(iter(cfilter.src_ids)) if cfilter.src_ids else "heldout-probe-01"

        pool = [
            {"id": src_id, "category": "identity_persona", "prompt": "A totally unique and novel question that has never been seen."}
        ]
        res = run_simula_campaign(
            prompt_pool=pool,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res["accepted_count"], 0)
        self.assertEqual(res["rejected_count"], 1)
        self.assertEqual(self.out_path.read_text().strip(), "")


class TestConcurrencyAndEdgeRobustness(unittest.TestCase):
    """Stress tests concurrency scaling and boundary edge cases."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.out_path = Path(self.tmpdir) / "s4_projection.jsonl"
        self.led_path = Path(self.tmpdir) / "spend.jsonl"

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_high_concurrency_64_workers_no_line_corruption(self):
        """Runs 64 workers on 64 distinct prompts; asserts every line in output is valid JSON with no corruption."""
        categories = get_taxonomy_categories()
        pool = []
        for i in range(64):
            cat = categories[i % len(categories)]
            pool.append({
                "id": f"stress_worker_{i:03d}",
                "category": cat,
                "prompt": f"Stress test question {i} regarding category {cat} in high concurrency.",
            })

        res = run_simula_campaign(
            prompt_pool=pool,
            concurrency_workers=64,
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )

        self.assertEqual(res["status"], "success")
        self.assertEqual(res["accepted_count"], 64)

        raw_lines = self.out_path.read_text().splitlines()
        valid_lines = [l for l in raw_lines if l.strip()]
        self.assertEqual(len(valid_lines), 64)

        for idx, line in enumerate(valid_lines):
            try:
                parsed = json.loads(line)
                self.assertIn("messages", parsed)
                self.assertIn("completion", parsed)
            except Exception as e:
                self.fail(f"Corrupted JSON line at index {idx}: {line[:80]} - error: {e}")

    def test_empty_prompt_pool_handled_gracefully(self):
        """Verifies empty prompt pool executes with zero errors and zero generation."""
        res = run_simula_campaign(
            prompt_pool=[],
            output_path=self.out_path,
            ledger_path=self.led_path,
            dry_run=True,
        )
        self.assertEqual(res["status"], "success")
        self.assertEqual(res["generated_count"], 0)
        self.assertEqual(res["accepted_count"], 0)
        self.assertEqual(res["rejected_count"], 0)


if __name__ == "__main__":
    unittest.main()
